name: Run on merged & approved PR

on:
  pull_request:
    types: [closed]

jobs:
  detect-env:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}
    outputs:
      env_name: ${{ steps.parse.outputs.result }}
    steps:
      - name: Decide env from base branch (develop → parse title, else → prod)
        id: setenv
        shell: bash
        env:
          BASE_REF: ${{ github.event.pull_request.base.ref }}
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          if [[ "$BASE_REF" == "develop" ]]; then
            t="${PR_TITLE,,}"
            if [[ "$t" =~ \[(.*[[:space:]])?(dev|zem)\b ]]; then
              echo "env_name=${BASH_REMATCH[2]}" >> "$GITHUB_OUTPUT"
            else
              echo "env_name=undefined" >> "$GITHUB_OUTPUT"
            fi
          else
            echo "env_name=prod" >> "$GITHUB_OUTPUT"
          fi

  use-env:
    needs: [detect-env]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Env is ${{ needs.detect-env.outputs.env_name }}"