name: Run on merged & approved PR

on:
  pull_request:
    types: [closed]

jobs:
  detect-env:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}
    outputs:
      env_name: ${{ steps.parse.outputs.result }}
    steps:
      - name: Parse PR title → env_name (dev|prod)
        id: parse
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const t = (context.payload.pull_request?.title || '').toLowerCase();
            // matches: [FEATURE DEV - ...] or [feature prod - ...]
            const m = t.match(/\[(?:[^\]]*?\s)?(dev|prod)\b/);
            return m ? m[1] : 'dev'; // fallback

  use-env:
    needs: [detect-env]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Env is ${{ needs.detect-env.outputs.env_name }}"